#if !canImport(ObjectiveC)
import XCTest

extension ResourceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ResourceTests = [
        ("testInit", testInit),
        ("testMap", testMap),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ResourceTests.__allTests__ResourceTests),
    ]
}
#endif
