#if !canImport(ObjectiveC)
import XCTest

extension CombineTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CombineTests = [
        ("testFailure", testFailure),
        ("testRequestFailure", testRequestFailure),
        ("testSuccess", testSuccess),
    ]
}

extension FetchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FetchTests = [
        ("testFailure", testFailure),
        ("testRequestFailure", testRequestFailure),
        ("testSuccess", testSuccess),
    ]
}

extension ResourceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ResourceTests = [
        ("testInit", testInit),
        ("testTryMap", testTryMap),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CombineTests.__allTests__CombineTests),
        testCase(FetchTests.__allTests__FetchTests),
        testCase(ResourceTests.__allTests__ResourceTests),
    ]
}
#endif
