#if !canImport(ObjectiveC)
import XCTest

extension ResourceCodableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ResourceCodableTests = [
        ("testDecode", testDecode),
    ]
}

extension ResourceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ResourceTests = [
        ("testInit", testInit),
        ("testTryMap", testTryMap),
    ]
}

extension ResourceURLSessionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ResourceURLSessionTests = [
        ("testFailure", testFailure),
        ("testSuccess", testSuccess),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ResourceCodableTests.__allTests__ResourceCodableTests),
        testCase(ResourceTests.__allTests__ResourceTests),
        testCase(ResourceURLSessionTests.__allTests__ResourceURLSessionTests),
    ]
}
#endif
